sudo: required
dist: xenial
branches:
  only:
    - master
language: c
compiler:
  - gcc
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
before_install:
  - sudo apt-get install -q -y colorgcc freeglut3-dev libgc-dev
install:
  - make fsim
script:
  - make check
