sudo: required
dist: xenial
branches:
  only:
    - master
language: c
compiler:
  - gcc
before_install:
  - sudo apt-get install -q -y colorgcc freeglut3-dev
install:
  - make test
script:
  - ./test
